### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by doubret** [ttous/inspector-amqp#9]
We should add a continuous integration validation.
Maybe TravisCI, i think it's free.
@rstiller would you mind helping us a little bit on this ?

**Comment by rstiller** [comment]
Depends on what you like to use. I use [travis-ci](https://travis-ci.org) as it's free and easy to use. @ttous would need to login into [travis-ci](https://travis-ci.org) using github as auth provider and sync his account.

Also a configfile like this is needed: https://github.com/rstiller/inspector-metrics/blob/master/.travis.yml  
it executes

`npm ci`
`npm test`

Of course this makes only sense if you have tests.

The full documentation can found here: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by ttous** [comment]
- My account is now linked to both Travis (CI) and David (dependencies).
- The configuration file `.travis.yml` was added to the root of the repository.
- The "build" and "dependencies" tags were added to the `README.md`.
